php:
  preset: laravel
  version: 8
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.app.blade.php
      - server.app.blade.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
